sudo: false

language: nix
nix: 2.2.1

env:
  global:
    - PYTHON=36

script:
  - nix-build -A python$PYTHON.pkgs.acoustics release.nix
  - nix-build -A python$PYTHON.pkgs.acoustics.sdist release.nix -o dist

deploy:
  provider: script
  script: bash .deploy-from-travis.sh
  skip_cleanup: true
  on:
    tags: true

